# Generated by Django 5.1.4 on 2025-01-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_response_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='response',
        ),
    ]
