# Generated by Django 5.1.4 on 2025-01-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_response_orderresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order',
        ),
    ]
